//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.16 at 09:52:43 AM CAT 
//


package entelect.training.incubator.spring.bookings.rewards;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the entelect.training.incubator.spring.bookings.rewards package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: entelect.training.incubator.spring.bookings.rewards
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CaptureRewardsRequest }
     * 
     */
    public CaptureRewardsRequest createCaptureRewardsRequest() {
        return new CaptureRewardsRequest();
    }

    /**
     * Create an instance of {@link CaptureRewardsResponse }
     * 
     */
    public CaptureRewardsResponse createCaptureRewardsResponse() {
        return new CaptureRewardsResponse();
    }

    /**
     * Create an instance of {@link RewardsBalanceRequest }
     * 
     */
    public RewardsBalanceRequest createRewardsBalanceRequest() {
        return new RewardsBalanceRequest();
    }

    /**
     * Create an instance of {@link RewardsBalanceResponse }
     * 
     */
    public RewardsBalanceResponse createRewardsBalanceResponse() {
        return new RewardsBalanceResponse();
    }

}
